server {
    server_name giganet.tvchurch.click;
    root /var/www/giganet/public;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /proxy/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /adminer/ {
        index index.php;
        try_files $uri $uri/ /adminer/index.php;
    }

    location ~ ^/adminer/.*\.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/giganet.tvchurch.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/giganet.tvchurch.click/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = giganet.tvchurch.click) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name giganet.tvchurch.click;
    return 404;
}
